//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASSIGNMENTMID.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int id { get; set; }
        public int Restaurantid { get; set; }
        public string Request1 { get; set; }
        public System.DateTime deadline { get; set; }
        public string isAssigned { get; set; }
        public Nullable<int> Employeeid { get; set; }
        public string isCollected { get; set; }
        public string isDelivered { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Restaurant Restaurant { get; set; }
    }
}
